name: Auto Generate Image Gallery

on:
  push:
    branches:
      - '**'

jobs:
  generate-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run image gallery script
        run: python readmegen.py

      - name: Commit gallery updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add */README.md
          git commit -m "Auto-update image gallery in subfolders" || echo "No changes to commit"
          git push
